# Generated by Django 2.1.7 on 2019-02-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('grade_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('units', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwa.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwa.users'),
        ),
    ]
